import type { Metadata } from "next";
import { Geist, Geist_Mono, Odibee_Sans, Poppins} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const odibee = Odibee_Sans({
  variable: "--font-odibee-sans",
  subsets: ["latin"],
  weight: "400"
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${odibee.variable} ${poppins.variable} antialiased bg-slate-100`}
      >
        {children}
      </body>
    </html>
  );
}
